name: graphq_ir_new

channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - conda
  # - cudatoolkit=11.8.0
  - python=3.8.*
  - pip=23.1.*

  - pip:
    - antlr4-python3-runtime==4.9.*
    - argparse==1.4.*
    - graphq-trans==0.1.*
    - huggingface-hub==0.16.*
    - numpy==1.23.*
    - torch==2.0.*
    - tqdm==4.65.*
    - transformers==4.30.*
    - rdflib==6.3.*
    - pandas==2.0.*
